### ISSUE TITLE
Add a UI to allow the user to change the keyboard/gmaepad binding

### ISSUE THREAD

**Issue by codewithpassion** [OpenROV/openrov-software#258] opened 2014-07-11 01:00 UTC
Currently, the bindings are fixed by the plugin developer. 
There is a settings page for the input controller with a read only list of bindings.

# Desired implementation:
* As a user, I would like to open a setting dialog where I can select the command I want to configure.
* Then I can press a key (keyboard) / button (gamepad) to bind this action to.
* If a key/button is already used, I can see this in the UI and can choose to override the duplicate assignment
* The keyboard information popover should reflect my changes
* my changes are persisted.

**Comment by BrianAdams** [comment] 2015-03-23 20:24
Duplicate of #35  but with a specification

**Closed by BrianAdams** 2015-03-23 20:24 UTC
Labels: enhancements
